type: "descriptive"
semester: "SoSe 26"
categories: ["Deutsch Bundesbahn", "Verspätungen", "Öffentlicher Verkehr"]
title: "Pendeln in Deutschland (WiSe 25/26)"
description: "Analyse der Verspätungen bei der Deutschen Bahn und deren ökonomische Auswirkungen."
