type: "inference"
semester: "SoSe 25"
categories: ["RCT", "Diff-in-Diff", "Marketing"]
title: "Kostentransparenz (SoSe 25)"
description: "Chancen und Potenziale der Kostentransparenz für Unternehmen"
